CREATE TABLE Throw (
    ID INT PRIMARY KEY IDENTITY,
    FrameID INT NOT NULL,
    ThrowNumber INT NOT NULL UNIQUE,
    PinsHit INT CHECK (PinsHit BETWEEN 0 AND 10) NOT NULL,
    FOREIGN KEY (FrameID) REFERENCES Frame(ID) ON DELETE CASCADE ON UPDATE CASCADE
);
